version: '3.7'

services:
  web:
    build: .
    command: python /code/manage.py runserver 0.0.0.0:8000
    environment:
      - SECRET_KEY=7(g@9i^t9qlfm%jzh)#g49odkk3yli+qhvykw%8)iw5#3i*jsd
      - DEBUG=1
    volumes:
      - .:/code
    ports:
      - 8000:8000
  
  db:
    image: postgres:11
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  
volumes:
  postgres_data: